steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "tristanbarlowgriffin.co.uk",
        "--build-arg",
        "KEY=$_MY_KEY",
        "-t",
        "gcr.io/personal-251317/tbg",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/personal-251317/tbg"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "tbg",
        "--image",
        "gcr.io/personal-251317/tbg",
        "--region",
        "europe-west1",
        "--memory",
        "2Gi",
        "--platform",
        "managed",
      ]

timeout: 1200s
