FROM node:12-slim

ENV MODE prod
ENV KEY ${KEY}

WORKDIR /usr/src/app
COPY . .
RUN yarn

RUN yarn build 
WORKDIR /usr/src/app/server
# Run the web service on container startup.
CMD ["yarn", "ts-node", "src/index.ts" ]