FROM node:12-slim

ENV MODE prod

WORKDIR /usr/src/app
COPY server server
COPY website website

WORKDIR /usr/src/app/server
RUN yarn --production

# Run the web service on container startup.
CMD [ "ts-node", "src/index.ts" ]