name: Deploy tbarlowg.com

on:
  push:
    tags:
      - tbg/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/setup
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: tbarlowg.com
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
