name: Deploy tbarlowg.com

on:
  push:
    tags:
      - tbg/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: GCP - Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: GCP - Setup
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - uses: hashicorp/setup-terraform@v3
      - uses: ./.github/workflows/setup

      - name: PNPM Pack
        working-directory: tbarlowg.com
        run: pnpm --filter @tbg/api --prod deploy packed

      - name: GCP - Configure Docker
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Docker - Build, Push
        working-directory: tbarlowg.com
        run: |
          docker build -t europe-west1-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/api/latest .
          docker push europe-west1-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/api/latest

      - name: Deploy
        working-directory: tbarlowg.com/deploy
        run: TF_VAR_gcp_project_id='${{secrets.GCP_PROJECT_ID}}' terraform apply
