# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno and run tests across stable and nightly builds on Windows, Ubuntu and macOS.
# For more information see: https://github.com/denolib/setup-deno

name: Deploy tbarlowg.com

on:
  push:
    tags:
      - tbg/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: GCP - Setup
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - uses: hashicorp/setup-terraform@v3
      - uses: ./.github/workflows/setup

      - name: PNPM Pack
        working-directory: tbarlowg.com
        run: pnpm --filter @tbg/api --prod deploy packed

      - name: GCP - Configure Docker
        run: gcloud auth configure-docker

      - name: Docker - Build, Push
        working-directory: tbarlowg.com
        run: |
          docker build . -t gcr.io/${{secrets.GCP_PROJECT_ID}}/tbg
          docker push gcr.io/${{secrets.GCP_PROJECT_ID}}/tbg

      - name: Deploy
        run: TF_VAR_gcp_project_id='${{secrets.GCP_PROJECT_ID}}' terraform apply
