name: Lint & Build

on: [pull_request]

jobs:
  lint-build:
    name: Lint & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/setup
      - run: pnpm -r lint
